// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrsnbmrxliomppcgvvek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indyc25ibXJ4bGlvbXBwY2d2dmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTA3OTQsImV4cCI6MjA2NzYyNjc5NH0.BEsABhfjK8jcC6qx1Yin8WG3kUoyNrcSHSywHJDDvaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});